name: Package compiled test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    build:
        name: Create wheel package
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: '3.x'
        - name: Install dependencies to build package
          run: |
            python -m pip install --upgrade pip
            pip install setuptools wheel
        - name: Build package
          run: |
            python setup.py sdist bdist_wheel
    
    test:
        env: 
          COMPILED_LIB_TEST: "true"
        name: Tests with wheel package
        needs: build
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            python-version: ["3.7", "3.8", "3.9", "3.10"]

        steps:
        - uses: actions/checkout@v3
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v3
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Test with pytest
          run: |
            pytest
